apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: arywatt/udagram-api-user:0.3.3
        name: backend-user
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: db-env
        - secretRef:
            name: eks-db-secrets
      restartPolicy: Always
